name: Generate Struct

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 12 * *' # Every day at 12pm UTC

jobs:
  check_schema_update:
    name: Check Schema Update
    runs-on: ubuntu-latest
    outputs:
      modified: ${{ steps.git-check.outputs.modified }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Schema Master Commit
        run: make schema_commit

      - name: Check for modified files
        id: git-check
        run: |
          modified=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
          echo "modified=${modified}" >> $GITHUB_OUTPUT

  generate_struct:
    name: Generate Struct
    runs-on: ubuntu-latest
    needs: check_schema_update
    if: needs.check_schema_update.outputs.modified == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: repo
      - name: Checkout Schema
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: api-data
          repository: PokeAPI/api-data
      
      - uses: actions/setup-go@v4

      - name: Fetch Schema Master Commit
        working-directory: repo
        run: make schema_commit
      
      - name: Debug
        working-directory: repo
        run: |
          pwd
          ls -al
          ls -al ..
      
      - name: Debug Schema
        working-directory: api-data
        run: |
          pwd
          ls -al
      
      - name: Register Commit Hash
        id: register_commit
        working-directory: repo
        run: |
          echo "commit_hash=$(cat SCHEMA_COMMIT)" >> $GITHUB_ENV

      - name: Generate Structs
        working-directory: repo
        run: make structs
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          path: repo
          commit-message: "[Bot] Update structs for commit ${{ env.commit_hash }}"
          title: 'Update structs for commit ${{ env.commit_hash }}'
          body: 'Update structs for commit https://github.com/jlord/sheetsee.js/commit/${{ env.commit_hash }} .'
          branch: external/generate-structs
          base: master
          labels: 'external'
          committer: schema-update[bot] <tzl19961216@gmail.com>
          delete-branch: true

  