name: Test

on: [push, workflow_dispatch]

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make All
        run: make

      - name: Update Coverage
        run: bash <(curl -s https://codecov.io/bash)